### ISSUE TITLE
paneState property never initalized

### ISSUE THREAD

**Issue by giffnyc** [erichoracek/MSDynamicsDrawerViewController#15]
Nice stuff...Thanks!

I had an older bit of code that uses a UINavigationController in the pane.  XCode can autogenerate some code for the app delegate application:supportedInterfaceOrientationForWindow:orientations method that assumes the root window controller is a UINavigationController when querying for the currently presented view controller so that it can determine supported rotations.  

After making your class the root view controller in this old app, I wrote a bit of code replacing the old auto-generated code to determine who was currently on the screen during the rotation - the master or the pane view controller.  When the app starts up, I saw that the property I was looking at, paneState, is never initialized.  I get a paneState ==  MSNavigationPaneStateOpen (i.e. BOOL NO, or integer 0) at app startup.

I assume this should be set to MSNavigationPaneStateClosed in the initialize method of the class.  I am currently setting it manually when I initialize the class as a working fix.   Or is it properly set elsewhere? Quite possibly my (BOOL) dyslexia is in full swing.  

Thanks

**Comment by erichoracek** [comment]
You're right—it's initialized to `MSNavigationPaneStateOpen` (by default, since that's the `0` value in the `enum`). Looks like it wasn't causing issues though in the example (as well as any apps I was using it in), as it's set to `MSNavigationPaneStateClosed` when you first set a pane view controller.

Good catch though—just pushed a fix.
