### ISSUE TITLE
Modifying the status bar transform can be potentially unsafe for the AppStore

### ISSUE THREAD

**Issue by LeoNatan** [erichoracek/MSDynamicsDrawerViewController#35]
Yes, you tried to hide it, great. Still very risky. I would suggest removing this code and figuring out a way to have the status bar remain in place. Perhaps find a way to set it to light or dark content by inspecting the drawer color.

**Comment by erichoracek** [comment]
If you don't want the `sharedApplication` to be queried for that key, just set the `shouldAlignStatusBarToPaneView` method to `NO` on your `MSDynamicsDrawerViewController` instance. The `statusBar` key won't show up in a `strings` dump, and it will never be invoked either.

**Comment by iltercengiz** [comment]
Mailbox should be a good example that proves it to be App Store safe.
![photo-110](https://f.cloud.github.com/assets/1618181/1911589/95513094-7d2e-11e3-84ec-e3782910b183.png)

**Comment by LeoNatan** [comment]
Gmail app used to have status bar notifications, which are normally forbidden. Some apps got rejected while gmail app was still there. Eventually Google removed the code after a warning from Apple. 

Just because there is an exception does not mean it's not risky. 

Thanks,
Leo Natan

**Comment by stel** [comment]
It seems that Mailbox makes a screenshot of the status bar (clocks stop when you move a panel) and hides it. It doesn't move the status bar view. It is more safer solution.
See more examples here: http://stackoverflow.com/questions/19007694/moving-status-bar-in-ios-7

**Comment by erichoracek** [comment]
To do it the way that mailbox supposedly does (with screenshots), you'd have to be a little more clever—something that I started down the path of implementing earlier but haven't yet released.

To make sure that the user is able to pull down notification center while the drawer is opened (and so that you don't get artifacts such as the full-screen notification center pull-tab included in your screenshot), you'd have to make the status bar always "visible" underneath your primary window, and take screenshots of it that are fed into a status bar proxy view within your primary window with a `windowLevel` of `UIWindowLevelStatusBar + 1`. However, this solution feels nearly as kludgy as a private API, since you'll always want to make sure that your status bar screenshots are up-to-date. This would get identical behavior to directly manipulating the status bar w/o private APIs though, so it might be a worthwhile endeavor.

**Comment by erichoracek** [comment]
@stel If Mailbox were just hiding it when the drawer was opened, the notification center pull tab would be exposed on a pull-down gesture when the drawer was opened (as far as I know). I think they're being slightly more clever about it (see above).

**Comment by Legoless** [comment]
I'm not exactly sure how Mailbox handles this, but I've struggled to take a screenshot with status bar present. Even TweetBot 3 takes screenshot of view hierarchy without status bar. We all know the status bar is in another window, so taking a snapshot of keyWindow will not generate it correctly. I currently do not know any method to take screenshot of status bar (please point me to a location), if even possible without private API. Besides, we have multiple applications with this functionality enabled in App Store and Apple doesn't seem to mind much.
