### ISSUE TITLE
The contents of the pane are unusable when a drawer is open

### ISSUE THREAD

**Issue by kefoo** [erichoracek/MSDynamicsDrawerViewController#47]
I'm using the control in an iPad app and want the user to be able to interact with the contents of the pane when a drawer is open, but all taps in the pane cause it to close even if they're on a control. If I turn off tap to close the taps are ignored. I've poked around the gesture recognizers for a while but can't get it to work. Is what I'm after doable?

Something unexpected I noticed is in gestureRecognizer:shouldReceiveTouch: touch.view varies depending on whether a drawer is open or not. When no drawer is open touch.view is the child of paneView. When a drawer is open touch.view is paneView itself.

**Comment by fcanas** [comment]
This is by design, though you can work around it. I've never seen an app that allows the user to interact with the center pane when a drawer is open.

Try `drawerViewController.paneViewController.view.userInteractionEnabled = YES` after the drawer is opened. Or you could override `-setPaneViewControllerViewUserInteractionEnabled:` on the drawer view controller with an empty implementation. Then user interaction will never be overridden by the drawer view controller.

**Comment by kefoo** [comment]
Of course it had to be something simple. Thank you.
