### ISSUE TITLE
panDelta variable not initialized - Clang Static Analyzer warning

### ISSUE THREAD

**Issue by Timac** [erichoracek/MSDynamicsDrawerViewController#49]
When running the Clang Static Analyzer on MSDynamicsDrawerViewController, it reports a logic error "Result of operation is garbage or undefined".

The file MSDynamicsDrawerViewController.m contains the method -[MSDynamicsDrawerViewController  panePanned:] which has an uninitialized variable 'panDelta'. In some cases it is possible that this variable is not initialized at all leading to possible random behavior.

The fix consists at replacing the line:
CGFloat panDelta;
by
CGFloat panDelta = 0;

![warning](https://f.cloud.github.com/assets/738543/1752795/a707a37c-662c-11e3-931a-101a299f40f5.png)

**Comment by fcanas** [comment]
Have you observed any ill behavior because of this?

`self.possibleDrawerDirection` cannot be clear on both the horizontal and vertical directions. If so, the behavior is completely undefined. You'd be patching an analyzer warning, but not actually correcting behavior. It may be more correct to assert that `possibleDrawerDirection` must have either horizontal or vertical components.

**Comment by Timac** [comment]
I am testing MSDynamicsDrawerViewController and I haven't see any ill behavior yet.

When I evaluate source code, I always run the Clang Static Analyzer on it before doing anything else. When I see source code containing hundreds of memory leaks or other analyzer warnings I know the code is bad and it is not worth looking at it.

Regarding the issue, I would initialize panDelta to 0.0 to make sure there is no undefined behavior and to avoid the analyzer warning. I haven't looked  at 'self.possibleDrawerDirection' but having an assert for undefined cases is always good.

**Comment by erichoracek** [comment]
Fixed in `1.3.2`.
