### ISSUE TITLE
Screen gets frozen after setPaneViewController

### ISSUE THREAD

**Issue by wolffan** [erichoracek/MSDynamicsDrawerViewController#84]
When I trigger the setPaneViewController: programatically because an event happened (a remote notification for example) or setPaneViewController gets executed inside a callback.

The paneViewController does move and displays the proper screen, but then gets frozen preventing any further interaction with the screen. 

I tried puting setPaneViewController inside a dispatch call on the main thread and on a performSelectorOnMainThread, but any of those worked.

**Comment by wolffan** [comment]
More:
Placing a selectorWithDelay on main thread on any screen will also froze the screen.
The selector will fire a method that will call setPane

**Comment by ChrisGrant** [comment]
+1

@wolffan I'm having the same problem. Did you manage to fix this?

**Comment by wolffan** [comment]
Sorry @ChrisGrant didn't

**Comment by ChrisGrant** [comment]
@wolffan Okay i'll try and take a look and see if I can open a PR.

**Comment by ChrisGrant** [comment]
I've made some progress here (for my use case).

It turns out that it happens when I call the following line when the pane state is **already** in the **MSDynamicsDrawerPaneStateClosed** state:

```
[self setPaneState:MSDynamicsDrawerPaneStateClosed animated:YES allowUserInterruption:NO completion:{ ... }
```

The important part here is calling the method with allowUserInterruption:**NO**. When I call it with **YES** the bug doesn't appear. 

I haven't been able to confirm this yet, but I _believe_ that the problem here is the following:
1. The _-(void)setPaneState:(MSDynamicsDrawerPaneState)paneState inDirection:(MSDynamicsDrawerDirection)direction animated:(BOOL)animated allowUserInterruption:(BOOL)allowUserInterruption completion:(void (^)(void))completion_ method is called. On [this line](https://github.com/monospacecollective/MSDynamicsDrawerViewController/blob/master/MSDynamicsDrawerViewController/MSDynamicsDrawerViewController.m#L776), the controller's view is set to UserInteractionEnabled:NO, so the user can't interrupt.
2. The dynamicAnimatorCompletion block is set a couple of lines later. This includes the functionality to set the view's userInteractionEnabled property back to YES, so that the user can interaction with the view again.
3. Usually, the - (void)dynamicAnimatorDidPause:(UIDynamicAnimator_)animator delegate method is called, [here](https://github.com/monospacecollective/MSDynamicsDrawerViewController/blob/master/MSDynamicsDrawerViewController/MSDynamicsDrawerViewController.m#L1355). This method *should_ call the dynamicAnimatorCompletion block, which will set the view's interaction back to enabled, then call the user's completion block (if it exists). However, if the state is the same, then the UIDynamicAnimator does nothing. This means that the pause method is not called, so the completion block is never called.

That's as far as I've got, but I'll try and work on a fix and open a PR soon.

**Comment by erichoracek** [comment]
@ChrisGrant @wolffan great find. I think the solution is to place guards in the `setPaneState...` method instead of calling the dynamic animator completion at the beginning of the method (since it didn't even run!). Check out 68cfb6f5bb62d7cbc53c314bf7db407ab1f36e07, and let me know if you see any issues what that implementation.

**Comment by ChrisGrant** [comment]
@eric-horacek Good point - I agree with that. Thanks for taking the time to look at my PR!
