### ISSUE TITLE
Private method used

### ISSUE THREAD

**Issue by ldesroziers** [erichoracek/MSDynamicsDrawerViewController#85]
I think you should really warn the developers in your readme file. You're using a private method (nicely hidden, but still…) here: https://github.com/monospacecollective/MSDynamicsDrawerViewController/blob/master/MSDynamicsDrawerViewController/MSDynamicsDrawerViewController.m%3B#L709-L717

**Comment by ldesroziers** [comment]
I'd like to add a little bit of my experience to that.
I've already called private methods into my app, and it has been approved successfully. However, v2 of my app had much more success than the first one, and it seems that some engineer at Apple gave a try to it and found out that I did something which is typically not allowed. I've passed through the pre-approval and approval processes because I used some tricks like the developer did on MSDynamicsDrawerViewController.
So yep, approval will be fine, but if you're app goes into the hand of an Apple Engineer, you gonna have some problems.

**Comment by nfranke** [comment]
Good catch. That is annoying and not really necessary. Seems they knows it's bad since it's obscured. Removing it seems to have no ill effect, other than that the status bar doesn't slide. However, the status bar doesn't slide open pinned to the view anyway. There appears to be a lag, so I figure just remove this part of the code.
